import NumPy

In [6]:
import numpy

ar = numpy.array([1, 2, 3, 4, 5])

print(ar)


[1 2 3 4 5]


In [7]:
import numpy as np

ar = np.array([1, 2, 3, 4, 5])

print(ar)


[1 2 3 4 5]


Create NumPy ndarray Object using array() function.

In [ ]:
import numpy as np

ar = np.array([1, 2, 3, 4, 5])

print(ar)

print(type(ar)) #It tells type of object passed to it.

Dimensions in Arrays:

2-D Arrays

In [ ]:
import numpy as np

ar = np.array([[4, 5, 6], [7, 8, 9]])

print(ar)

3-D arrays

In [ ]:
import numpy as np

ar = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [40, 50, 60]]])

print(ar)

In [ ]:
# ndim attribute returns an integer that tells how many dimensions array have.
import numpy as np

a = np.array(10)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[4, 5, 6], [7, 8, 9]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [40, 50, 60]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [8]:
import numpy as np

ar = np.array([1, 2, 3, 4,5], ndmin=6)

print(ar)
print('Number of dimensions :', ar.ndim)

[[[[[[1 2 3 4 5]]]]]]
Number of dimensions : 6


Access Array Elements

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

print(arr[1] + arr[3])

1
2
3
4
6


In [11]:
# Accessing 3-D arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 2])


9


In [12]:
# Negative Indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -3])


Last element from 2nd dim:  8


Array Slicing

In [13]:
import numpy as np

ar = np.array([1, 2, 3, 4, 5, 6, 7])

print(ar[1:5])

print(ar[2:])#elements from index 2 to the end of the array

print(ar[:5])#elements from the beginning to index 5 (not included)

print(ar[-3:-1])#negative slicing

[2 3 4 5]
[3 4 5 6 7]
[1 2 3 4 5]
[5 6]


In [14]:
# 2-D array
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])#From the first element, slice elements from index 1 to index 4 

print(arr[0:3, 3])#From both elements, return index 3

print(arr[0:2, 1:4])#From both elements, slice index 1 to index 4 

[2 3 4]
[4 9]
[[2 3 4]
 [7 8 9]]


Copy & View

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 10

print(arr)
print(x)

#view
y = arr.view()
arr[3] = 40
print(arr)
print(y)

[10  2  3  4  5]
[1 2 3 4 5]
[10  2  3 40  5]
[10  2  3 40  5]


Shape of an array

In [ ]:
#It is no. of elements in each dimension.
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


In [ ]:
#Reshaping arrays
import numpy as np

ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

x = ar.reshape(4,3)

print(x)

In [ ]:
#Converting Multidimensional array into 1D array using reshape(-1)
import numpy as np

ar = np.array([[1, 2], [4, 5]])

x = ar.reshape(-1)

print(x)

In [ ]:
#Iteration using ndenumerate()
import numpy as np

ar = np.array([1, 2, 3,4,5])

for idx, x in np.ndenumerate(ar):
  print(idx , x)

In [ ]:
#Joining arrays
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


In [ ]:
#Splitting arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

x = np.array_split(arr, 2)

print(x)

In [ ]:
#Searching arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 5])

x = np.where(arr == 5)

print(x)

In [ ]:
#Sorting arrays
import numpy as np

ar = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(ar))